version: 2
updates:
- package-ecosystem: maven
  directory: "/java-template"
  schedule:
    interval: monthly
    time: "04:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: org.assertj:assertj-core
    versions:
    - 3.18.1
  - dependency-name: org.mockito:mockito-junit-jupiter
    versions:
    - 3.6.28
  - dependency-name: org.mockito:mockito-core
    versions:
    - 3.6.28
- package-ecosystem: maven
  directory: "/groovy-template"
  schedule:
    interval: monthly
    time: "04:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: org.codehaus.gmavenplus:gmavenplus-plugin
    versions:
    - 1.12.0
- package-ecosystem: maven
  directory: "/kotlin-template"
  schedule:
    interval: monthly
    time: "04:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: org.jetbrains.kotlin:kotlin-maven-plugin
    versions:
    - 1.4.21-2
  - dependency-name: org.jetbrains.kotlin:kotlin-stdlib
    versions:
    - 1.4.21-2
  - dependency-name: io.mockk:mockk
    versions:
    - 1.10.4
  - dependency-name: org.assertj:assertj-core
    versions:
    - 3.18.1
