version: 1
update_configs:
  - package_manager: "java:maven"
    directory: "/java-template"
    update_schedule: "monthly"
  - package_manager: "java:maven"
    directory: "/groovy-template"
    update_schedule: "monthly"
  - package_manager: "java:maven"
    directory: "/kotlin-template"
    update_schedule: "monthly"
